include:
  # package:surf_lint_rules/analysis_options.yaml
  package:very_good_analysis/analysis_options.yaml

# https://dart.dev/tools/analysis#changing-the-severity-of-rules
analyzer:
  errors:
    depend_on_referenced_packages: error
    # For freezed annotation used in factory constructor.
    invalid_annotation_target: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.mapper.dart

linter:
  rules:
    flutter_style_todos: false
