name: kdays_client
description: 'KDays客户端'
homepage: 'https://github.com/realth000/tsdm_client'
repository: 'https://github.com/realth000/tsdm_client'
issue_tracker: 'https://github.com/realth000/tsdm_client/issues'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  convert: ^3.1.1
  crypto: ^3.0.3
  dio: ^5.4.3+1
  drift: ^2.18.0
  drift_dev: ^2.18.0
  envied: ^0.5.4+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  path: ^1.9.0
  path_provider: ^2.1.3
  responsive_framework: ^1.4.0
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.24
  talker: ^4.2.4

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
